### PR TITLE
adds some @jakearchibald

### PR DESCRIPTION
**Pull request by dotcode**
… because everything needs more @jakearchibald

### CODE REVIEW

**Comment by dotcode** [comment]
( … just added @jakearchibald in the hope he can provide the :+1:)

**Comment by benjclark** [comment]
Was it your intention for them to list underneath each other? At the mo the references are on the same line

**Comment by dotcode** [comment]
Doh! Should have been in a list as well - thanks for spotting :)

**Comment by benjclark** [comment]
👍

**Pull request merged**
