### PR TITLE
add ES2015 variables

### PR DESCRIPTION
**Pull request by dotcode**

### CODE REVIEW

**Comment by hollsk** [comment]
Looks great. Should we also specify strict mode? I don't know what the Shunter convention is, but it's generally recommended elsewhere.

**Comment by danyalaytekin** [comment]
:+1:

**Comment by rowanmanning** [comment]
Something I'm doing now, which might be worth adding here if you agree, is using `const` everywhere unless a variable _explicitly_ needs to be modified. It's great for the default state of a variable to be immutable, and I've found that I actually have very little need to use `let`.

There's some good background here: https://ada.is/blog/2015/07/13/immutable/

**Comment by dotcode** [comment]
Thanks @rowanmanning - better now?

**Pull request merged**
