### PR TITLE
add javascript "Error handling" section

### PR DESCRIPTION
**Pull request by dotcode**
Create error handling subsection under "Blocks", re-title previous "Error handling" section as "Strict mode".

Addresses #75

### CODE REVIEW

**Comment by hollsk** [comment]
"You should assume that your code will fail, and take steps to handle those failures" would make more sense at the start of the "error handling" subsection, i reckon - it's an introductory phrase, really. Otherwise 👍

**Comment by dotcode** [comment]
… although … do you think it's a better introductory phrase to the strict mode stuff than the try/catch stuff?

**Comment by hollsk** [comment]
Not strictly (haha see what i did there? geddit?!). Adding a try/catch is literally, by definition, assuming that your code will fail, and writing something to handle that assumed failure. 

IMO "error handling" and "strict mode" are conceptually linked, as the purpose of strict mode is to enable better/saner error handling.

**Comment by dotcode** [comment]
Yeah, I agree with all that. I suppose … I think it's a better introductory phrase to the strict mode stuff than it is to the try/catch stuff, because the try/catch stuff is purely about formatting, whereas the strict mode is more about methodology.

**Comment by dotcode** [comment]
those two sections - as they currently exist - obviously could be written in a better manner (as evidenced by this discussion :)

I've had an idea (my only one of the week, so be gentle). How about moving the try/catch stuff out of "Blocks" and sticking it under "Error handling"? Would that work?

**Comment by hollsk** [comment]
¯\_(ツ)_/¯

The confusion is down to me not realising the strict mode section existed in the Nature Playbook, so I've reinvented the wheel. The difference between my commit and the previous work is just that I've interpreted the concept of strict mode as being a subset of "error handling", where the other author treated them as separate concepts. 

You could remove the entire controversy by deleting my intro line entirely, which would bring into line with the Nature Playbook :p

**Comment by dotcode** [comment]
OK. I like your introduction. Works well as an introduction to the "strict mode" section, so going to just merge this. We can always revisit if we come up with anything better.

**Pull request merged**
