### PR TITLE
Delete "Nature runbook" mentioned in css.md

### PR DESCRIPTION
**Pull request by KaimingTao**
The URL of "Nature runbook", https://github.com/nature/playbook, is 404.

### CODE REVIEW

**Comment by dotcode** [comment]
Hi Kaiming! Thanks for this - interesting point - the "Nature runbook" _does_ exist, but it's not a public repo. Not sure how to handle this - the link is useful to people who work here and contribute to this section, but obviously confusing to people outside the org. Maybe alter to mention that this is a private repo?

Something along the lines of "Nature runbook (private repo)"?

**Comment by KaimingTao** [comment]
Hi, I would like to ask a question. If you mark this "Nature runbook" as a private repo, will it violate the CC license? If not, then I think that's the best option.

**Comment by dotcode** [comment]
Hi Kaiming ... I'll detail why we're developing this in the open tomorrow, when I'm back in the office. Important point, so may take me a little while :)

**Comment by dotcode** [comment]
Closing this, awaiting new PR with different link text.

**Pull request closed without merging**
