### PR TITLE
Add outline of javascript directory structure

### PR DESCRIPTION
**Pull request by andrewmee**
Putting this forward as a proposal - please do feel free to offer alternative names, structures, definitions, etc.

### CODE REVIEW

**Comment by dotcode** [comment]
LGTM

**Comment by benjclark** [comment]
What are the SN.Component and SN.util objects? Does this refer to the global objects within a project that are responsible for those functions?

**Comment by andrewmee** [comment]
@benjclark Just neat places to namespace our JS into which reflect what kind of JS it is (DOM-binding or non, etc.).  The idea being when you see a call for `SN.util.X` you've got a good idea about what kind of script that is referencing (and where to find it in the `resources/js/*` directory structure).

**Comment by benjclark** [comment]
Thanks 👍

**Pull request merged**
